### ISSUE TITLE
여기서 에러발생!

### ISSUE THREAD

**Issue by jinwoo1225** [2021-HKNU-CD/blockchain-horse-racing#2]
https://github.com/2021-HKNU-CD/blockchain-horse-racing/blob/ddcf13795bed489d4600f34c56b89daf82933212/HorseRacingGame.sol#L48

this가 무엇인지를 나도 모르겠던데?...

**Comment by GGob2** [comment]
현재 짜여진 코드에서는
` players[index].playerAddress.transfer(address(this).balance);`
로 작성해야 문제가 해결되는 것 같습니다. 

근데 지금 코드를 보니까 전체적으로 다시 짜야할 것 같아서 수정 후, push 하겠습니다.

**Comment by jinwoo1225** [comment]
아 playerAddress.. 이걸생각을 못했네 ㅋㅋ

**Comment by jinwoo1225** [comment]
어떤 식으로 재작성하시죠?

**Comment by GGob2** [comment]
구조체를 사용 안하는 게 나중에 보더라도 깔끔할 것 같아서 현재 구조체를 제외한 뒤 코드를 작성하는 중입니다!

**Comment by GGob2** [comment]
> 아 playerAddress.. 이걸생각을 못했네 ㅋㅋ

제가 코드 작성 시 Compile 없이 짜는바람에 발생한 문제입니다 😢

**Comment by jinwoo1225** [comment]
아하!! 구조체는 그대로 유지해도 좋을것 같아요!
Address 타입에 transfer가 들어있다는 사실을 모르고 있어서 this가 뭘지칭하는지를 몰랐어요...

**Comment by GGob2** [comment]
제가 Clean Coder가 아니라서 발생한 문제입니다 흑흑 😭
